# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 15
  - name: Researches
    url: tags/
    weight: 25
  - name: Events
    url: tags/
    weight: 35
  - name: Contact me
    url: tags/
    weight: 45
