# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 20
  - name: Researches
    url: tags/
    weight: 30
  - name: Events
    url: tags/
    weight: 40
  - name: Contact me
    url: tags/
    weight: 50
